# Generated by Django 6.0.3 on 2026-03-13 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chance', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('Guaranteed unique', 'Guaranteed unique'), ('Additional item', 'Additional item')], max_length=100)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main_app.boss')),
            ],
        ),
    ]
