# Generated by Django 6.0.3 on 2026-03-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='chance',
            field=models.CharField(max_length=100),
        ),
    ]
