# Generated by Django 6.0.3 on 2026-03-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_item_category_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pass',
            name='img',
            field=models.TextField(default=''),
        ),
    ]
